# Generated by Django 4.0 on 2022-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0012_eventdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
