# Generated by Django 4.0 on 2022-01-24 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0013_eventdetails_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Gender', models.CharField(max_length=10)),
                ('Dob', models.DateField()),
                ('salary', models.IntegerField()),
                ('experience', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
    ]
