# Generated by Django 4.0 on 2022-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0014_staffdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male'), ('Others', 'others')], max_length=10),
        ),
    ]
