# Generated by Django 4.0 on 2022-01-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0015_alter_staffdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='EventType',
            field=models.CharField(choices=[('Wedding', 'wedding'), ('Birthday', 'birthday'), ('Corporate', 'corporate'), ('Social Gathering', 'social gathering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male'), ('Others', 'others')], max_length=10),
        ),
    ]
