# Generated by Django 4.0 on 2022-02-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('BeEventful', '0016_alter_eventdetails_eventtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Menu', models.CharField(max_length=50)),
                ('Details', models.TextField()),
                ('Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('Eve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeEventful.eventdetails')),
            ],
        ),
    ]
