# Generated by Django 4.0 on 2022-02-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0017_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Date',
            new_name='BookingDate',
        ),
    ]
